---
abstract: "Perl extension for interfacing with a NES controller from the Raspberry Pi's GPIO ports."
author:
  - 'Chris Kloberdanz <klobyone@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Device-BCM2835-NES
no_index:
  directory:
    - t
    - inc
requires:
  Device::BCM2835: 1.3
version: 0.02
